### ISSUE TITLE
No images shown in front of the forum titles and topic titles

### ISSUE THREAD

**Issue by wootje** [cabot/damaio#18]
There are no mages shown in front of the forum titles and topic titles.
![NoImages](https://github.com/user-attachments/assets/fefc84c5-1a77-4b47-8b21-f569ca8cf78f)

**Comment by cabot** [comment]
Hello,

Can you provide a link to your board?

**Comment by wootje** [comment]
https://androidtvboxreviews.com
________________________________

**Comment by wootje** [comment]
I already found the issue.

The following code in the "base.css" file in your template forced the background to be "none". 
`.row-item[class*="_read"],
.row-item[class*="_unread"],
.row-item.forum_link,
.row-item.topic_moved {
	background-image: none;
}`

I did removed the code and now the images are visible.

Do you have an icon pack with better images/icons? The stock images/icons are not very pretty.

**Comment by cabot** [comment]
This style uses the [Font Awesome icons font](https://fontawesome.com/v4/icons/) for status markers (read, unread, etc).
The original problem you're experiencing comes from the fact that you've changed the font family in this rule:
```css
.row-item[class*="_read"]::before,
.row-item[class*="_unread"]::before,
.forum_link::before,
.topic_moved::before,
.row-item[class*="_mine"]::after {
	font-family: 'Lexend';
	font-variant: normal;
	text-rendering: auto;
	position: absolute;
	top: 50%;
	transform: translateY(-50%);
}
```
Lexend is **not** an icon font.

In addition, by deleting this rule, you display the prosilver icons by inheritance:
```css
.row-item[class*="_read"], .row-item[class*="_unread"], .row-item.forum_link, .row-item.topic_moved {
	background-image: none;
}
```

**Comment by cabot** [comment]
Tip: did you know that there is an [extension](https://github.com/cabot/damaioconfiguration) that lets you configure certain elements of the style?

**Comment by dcsjapan** [comment]
If I may add a word of advice, as someone who modded damaïo back before the extension was available ...

If you don't want to use the extension, or would like to make changes that go beyond what the extension allows, a better approach would be to create a **child style** of damaïo and make your changes there. Then if something didn't work as expected, you could switch back and forth between damaïo and the child style and identify that the issue was occurring in your changes and not in damaïo. 😉 

@cabot Thanks for all your great work on this phpBB style, it's one of the best around!

**Comment by wootje** [comment]
> Tip: did you know that there is an [extension](https://github.com/cabot/damaioconfiguration) that lets you configure certain elements of the style?

Thank you. I did install the plugin and added custom CSS. Everything is looking good now.

Thank you!

**Comment by cabot** [comment]
You are not declaring the font correctly, I suggest you import it directly from Google Fonts.
Based on the selectors you used, something like this should be sufficient:

```css
@import url('https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap');
body,
h1,
h2,
h3,
h4,
h5,
h6,
h7,
h8,
.entry-title
a.forumtitle,
.content,
fieldset,
.pagination li.active span,
dl.faq,
.button,
a.button1,
input.button1,
a.button2,
input.button2,
input.button3,
fieldset.polls {
	font-family: "Lexend", serif;
}
```
